# Generated by Django 4.2.6 on 2023-10-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(default='', max_length=1024)),
                ('option_2', models.CharField(default='', max_length=1024)),
                ('option_3', models.CharField(default='', max_length=1024)),
                ('option_4', models.CharField(default='', max_length=1024)),
                ('answer', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subjects')),
            ],
        ),
    ]
